steps:
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['install', 'test', './helm', '--namespace', 'sidespin', 
  '--set', 'pubsub', '${_PUBSUB}',
  '--set', 'name', '${_NAME}'
  ]
#  args: ['uninstall', 'test', '--namespace', 'sidespin']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
substitutions:
  _PUBSUB: FALSE
  _NAME: 'test'

tags: ['cloud-builders-community']