steps:
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['pull', 'stable/keel', '--untar']
  dir: '${_REPO_NAME}'
- name: 'bash'
  args: ['echo', 'I am running a bash command']
tags: ['cloud-builders-community']